### Numpy
Numpy is a fundemental library for scientific computing in Python. It provides supports for arrays and matrices, along with a collection of mathematical function to operate on these data structures. In this lesson, we will cover the basics of Numpy, focusing array and vectorized operations.


In [3]:

import numpy as np

## create array using numpy
# create a 1 D array

arr1=np.array([1,2,3,4,5]) #inside array the list is given
print(arr1)
print(type(arr1)) # the type is array
print(arr1.shape) # this is a single diemshion array show it is showing single 5 only 



[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
arr2=np.array([1,2,3,4,5]) 
arr2.reshape(1,5) # 1row and  5column # there is 2 square bracket so it is also called two dimensiosn array

array([[1, 2, 3, 4, 5]])

In [12]:
#2D array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [16]:
np.arange(2,10,2).reshape(4,1)


array([[2],
       [4],
       [6],
       [8]])

In [17]:
np.ones((3,4)) # creating 3 rows and 4 coulums and having the data only one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
#Identity matrix
np.eye(3) # diagonal have one 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
#Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element wise addition
print("Addition",arr1+arr2)
print("Substraction",arr1-arr2)


Addition [11 22 33 44 55]
Substraction [ -9 -18 -27 -36 -45]


In [10]:
arr1=np.array([[1,2,3,4,5],[3,4,5,6,7],[2,3,4,5,6]])
print(arr1)

print("Array using index accessing ",arr1[0,1])

[[1 2 3 4 5]
 [3 4 5 6 7]
 [2 3 4 5 6]]
Array using index accessing  2


In [12]:
# now accessing using slicing method
print(arr1[1:,2:])

[[5 6 7]
 [4 5 6]]


In [16]:
#Modifying array 
arr1[0,0]=100
print(arr1)


[[100   2   3   4   5]
 [  3   4   5   6   7]
 [  2   3   4   5   6]]


In [17]:
#or 
arr1[0][1]=200
print(arr1)

[[100 200   3   4   5]
 [  3   4   5   6   7]
 [  2   3   4   5   6]]


In [18]:
#Statistical concepts--Normalization
#to have a mean of 0 and standard deviation of 1
data=np.array([1,2,3,4,5])

#Calculate the mean and standard deviation
mean = np.mean(data)
std_dev=np.std(data)

#NOrmalize the data 
normalize_data=(data-mean)/std_dev
print("Normalizeed data :",normalize_data)

Normalizeed data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [19]:
#Logical operation
data=np.array([1,2,3,4,5,6,7,7,8,9])

data[data>5]

array([6, 7, 7, 8, 9])